import{TILE_SIZE,clamp,latLngToWorld,worldToLatLng}from'./map-utils.js?v=1.3.1';
export class SimpleMap{
constructor(el,o={}){this.el=el;this.center={lat:o.lat??18.7357,lng:o.lng??-70.1627};this.zoom=clamp(Math.round(o.zoom??8),2,19);this.interactive=o.interactive!==false;this.markers=[];this.draft=null;this.userLocation=null;this.onTap=()=>{};this.onMarkerTap=()=>{};this.onViewChange=()=>{};this.drag=null;this.buildLayers();if(this.interactive)this.bind();this.resizeObserver=new ResizeObserver(()=>this.render());this.resizeObserver.observe(this.el);this.render();}
buildLayers(){this.tileLayer=document.createElement('div');this.tileLayer.className='tile-layer';this.markerLayer=document.createElement('div');this.markerLayer.className='marker-layer';this.el.append(this.tileLayer,this.markerLayer);}
bind(){this.el.addEventListener('pointerdown',e=>{if(e.button!==0)return;this.el.setPointerCapture?.(e.pointerId);this.drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};});this.el.addEventListener('pointermove',e=>{if(!this.drag||this.drag.id!==e.pointerId)return;const dx=e.clientX-this.drag.lastX,dy=e.clientY-this.drag.lastY,total=Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY);if(total>7)this.drag.moved=true;if(dx||dy){const c=latLngToWorld(this.center.lat,this.center.lng,this.zoom),ll=worldToLatLng(c.x-dx,c.y-dy,this.zoom);this.center={lat:ll.lat,lng:nLng(ll.lng)};this.drag.lastX=e.clientX;this.drag.lastY=e.clientY;this.render();}});const end=e=>{if(!this.drag||this.drag.id!==e.pointerId)return;const moved=this.drag.moved;this.drag=null;if(!moved){const r=this.el.getBoundingClientRect();this.onTap(this.screenToLatLng(e.clientX-r.left,e.clientY-r.top));}else this.onViewChange({...this.center,zoom:this.zoom});};this.el.addEventListener('pointerup',end);this.el.addEventListener('pointercancel',()=>this.drag=null);this.el.addEventListener('wheel',e=>{e.preventDefault();this.setZoom(this.zoom+(e.deltaY<0?1:-1));},{passive:false});}
screenToLatLng(x,y){const c=latLngToWorld(this.center.lat,this.center.lng,this.zoom);return worldToLatLng(c.x+x-this.el.clientWidth/2,c.y+y-this.el.clientHeight/2,this.zoom);}
setView(lat,lng,zoom=this.zoom){this.center={lat:clamp(Number(lat),-85,85),lng:nLng(Number(lng))};this.zoom=clamp(Math.round(zoom),2,19);this.render();this.onViewChange({...this.center,zoom:this.zoom});}
setZoom(z){const n=clamp(Math.round(z),2,19);if(n===this.zoom)return;this.zoom=n;this.render();this.onViewChange({...this.center,zoom:this.zoom});}
setMarkers(m){this.markers=Array.isArray(m)?m:[];this.renderMarkers();}
setDraft(lat,lng){this.draft=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;this.renderMarkers();}
setUserLocation(lat,lng){this.userLocation=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;this.renderMarkers();}
fitPoints(points,maxZoom=16){if(!points?.length)return;if(points.length===1){this.setView(points[0].lat,points[0].lng,maxZoom);return;}const w=Math.max(120,this.el.clientWidth-100),h=Math.max(120,this.el.clientHeight-100);for(let z=maxZoom;z>=2;z--){const ps=points.map(p=>latLngToWorld(p.lat,p.lng,z));const xs=ps.map(p=>p.x),ys=ps.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);if(maxX-minX<=w&&maxY-minY<=h){const ll=worldToLatLng((minX+maxX)/2,(minY+maxY)/2,z);this.setView(ll.lat,ll.lng,z);return;}}}
render(){if(!this.el.clientWidth||!this.el.clientHeight)return;this.renderTiles();this.renderMarkers();}
renderTiles(){const w=this.el.clientWidth,h=this.el.clientHeight,c=latLngToWorld(this.center.lat,this.center.lng,this.zoom),left=c.x-w/2,top=c.y-h/2,minTx=Math.floor(left/TILE_SIZE)-1,maxTx=Math.floor((left+w)/TILE_SIZE)+1,minTy=Math.floor(top/TILE_SIZE)-1,maxTy=Math.floor((top+h)/TILE_SIZE)+1,n=2**this.zoom,f=document.createDocumentFragment();for(let ty=minTy;ty<=maxTy;ty++){if(ty<0||ty>=n)continue;for(let tx=minTx;tx<=maxTx;tx++){const img=document.createElement('img');img.className='map-tile';img.alt='';img.draggable=false;img.decoding='async';img.src=`https://tile.openstreetmap.org/${this.zoom}/${((tx%n)+n)%n}/${ty}.png`;img.style.left=`${Math.round(tx*TILE_SIZE-left)}px`;img.style.top=`${Math.round(ty*TILE_SIZE-top)}px`;f.append(img);}}this.tileLayer.replaceChildren(f);}
renderMarkers(){if(!this.markerLayer||!this.el.clientWidth)return;const w=this.el.clientWidth,h=this.el.clientHeight,c=latLngToWorld(this.center.lat,this.center.lng,this.zoom),left=c.x-w/2,top=c.y-h/2,world=2**this.zoom*TILE_SIZE,f=document.createDocumentFragment(),point=(lat,lng)=>{let p=latLngToWorld(lat,lng,this.zoom),dx=p.x-c.x;if(dx>world/2)p={...p,x:p.x-world};if(dx<-world/2)p={...p,x:p.x+world};return{x:p.x-left,y:p.y-top};};this.markers.forEach(m=>{const p=point(m.lat,m.lng);if(p.x<-50||p.y<-50||p.x>w+50||p.y>h+50)return;const b=document.createElement('button');b.type='button';b.className='marker'+(m.status==='completed'?' completed':'')+(m.isOverdue?' overdue':'');b.style.left=`${p.x}px`;b.style.top=`${p.y}px`;b.setAttribute('aria-label',`Abrir revisita ${m.name||''}`.trim());b.addEventListener('pointerdown',e=>e.stopPropagation());b.addEventListener('click',e=>{e.stopPropagation();this.onMarkerTap(m.id);});f.append(b);});if(this.draft){const p=point(this.draft.lat,this.draft.lng),d=document.createElement('div');d.className='marker draft';d.style.left=`${p.x}px`;d.style.top=`${p.y}px`;f.append(d);}if(this.userLocation){const p=point(this.userLocation.lat,this.userLocation.lng),d=document.createElement('div');d.className='user-dot';d.style.left=`${p.x}px`;d.style.top=`${p.y}px`;f.append(d);}this.markerLayer.replaceChildren(f);}}
function nLng(l){while(l>180)l-=360;while(l<-180)l+=360;return l;}
