const STORAGE_KEY='revisita.state.v1';
const SNAPSHOT_KEY='revisita.preimport.v1';
export function createDefaultState(){return{version:2,visits:[],settings:{theme:'dark'},map:{lat:18.7357,lng:-70.1627,zoom:8},lastSavedAt:null};}
export function loadState(){const f=createDefaultState();try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeState(JSON.parse(r)):f;}catch(e){console.warn('No se pudo leer el estado local.',e);return f;}}
export function normalizeState(value){const b=createDefaultState();if(!value||typeof value!=='object')return b;return{version:2,visits:Array.isArray(value.visits)?value.visits.map(normalizeVisit).filter(Boolean):[],settings:{...b.settings,...(value.settings||{})},map:{...b.map,...(value.map||{})},lastSavedAt:value.lastSavedAt||null};}
export function normalizeVisit(v){if(!v||typeof v!=='object')return null;const lat=Number(v.lat),lng=Number(v.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const status=v.status==='completed'?'completed':'active';return{id:String(v.id||crypto.randomUUID()),name:String(v.name||'Revisita'),address:String(v.address||''),notes:String(v.notes||''),dueDate:typeof v.dueDate==='string'?v.dueDate:'',dueTime:/^\d{2}:\d{2}$/.test(v.dueTime||'')?v.dueTime:'',status,completedAt:status==='completed'?(v.completedAt||null):null,history:Array.isArray(v.history)?v.history.map(h=>({completedAt:h.completedAt||'',dueDate:h.dueDate||'',dueTime:/^\d{2}:\d{2}$/.test(h.dueTime||'')?h.dueTime:''})).filter(h=>h.completedAt):[],lat,lng,createdAt:v.createdAt||new Date().toISOString(),updatedAt:v.updatedAt||new Date().toISOString()};}
export function saveState(state){state.version=2;state.lastSavedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return state.lastSavedAt;}
export function exportPayload(state){return{app:'Revisita',schemaVersion:2,exportedAt:new Date().toISOString(),visits:state.visits,settings:state.settings};}
export function validateImportPayload(payload){if(!payload||typeof payload!=='object')throw new Error('El archivo no contiene un objeto JSON válido.');if(payload.app!=='Revisita')throw new Error('Este archivo no parece ser una copia de Revisita.');if(!Array.isArray(payload.visits))throw new Error('La copia no contiene una lista de revisitas válida.');const visits=payload.visits.map(normalizeVisit).filter(Boolean);if(visits.length!==payload.visits.length)throw new Error('Una o más revisitas tienen coordenadas inválidas.');return{...payload,visits};}
export function previewImport(state,payload){const ids=new Set(state.visits.map(v=>v.id));const conflicts=payload.visits.filter(v=>ids.has(v.id)).length;return{imported:payload.visits.length,conflicts,newRecords:payload.visits.length-conflicts,localBefore:state.visits.length};}
export function applyImport(state,payload){localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(state));const merged=new Map(state.visits.map(v=>[v.id,v]));payload.visits.forEach(v=>merged.set(v.id,normalizeVisit(v)));state.visits=[...merged.values()];if(payload.settings?.theme)state.settings.theme=payload.settings.theme;saveState(state);return state;}
export function hasRecoverySnapshot(){return Boolean(localStorage.getItem(SNAPSHOT_KEY));}
export function restoreRecoverySnapshot(){const raw=localStorage.getItem(SNAPSHOT_KEY);if(!raw)throw new Error('No hay una copia anterior disponible.');const restored=normalizeState(JSON.parse(raw));saveState(restored);return restored;}
